export const projects = [
    {
        name: "OtakuGIFs",
        type: 'REST API & Website',
        description: "Free REST API that serves animated GIFs, WEBPs & AVIFs as reactions. Used mainly by Discord bot creators.",
        icon: "/otakugifsLogo.svg",
        technologies: ["React.js", 'TypeScript', 'SCSS', 'MongoDB', 'Fastify.js',],
        url: 'https://otakugifs.xyz',
        color: '#1761e1',
        roundIcon: false,
    },
    {
        name: "Kouhai",
        type: 'Website & API',
        description: "Utilities for every day use. Includes 5 easy to use features that make life easier. Why use 5 different websites when Kouhai has a URL Shortener, file upload and editing and can take screenshots of websites for you?",
        icon: "/kouhaiLogo.svg",
        technologies: ["SvelteKit", 'TypeScript', 'SCSS', 'MongoDB', 'BunnyCDN', 'sharp', 'puppeteer'],
        url: 'https://kouh.ai',
        color: '#a63dcf',
        roundIcon: false,
    },
    {
        name: "Shiro",
        type: 'Chatbot',
        description: "Multipurpose chatbot for Discord. Full moderation and auto-moderation, fun text-based games and guild logging. Currently in 4000+ guilds.",
        icon: "/shiroLogo.png",
        technologies: ["Node.js", 'Discord.js', 'MongoDB', 'dawdawdawdadadwada'],
        url: null,
        color: '#e05477',
        roundIcon: true,
    },
    {
        name: "Nyx",
        type: 'Chatbot',
        description: "Freelance project. Nyx is a Discord bot that gives you XP and Currency depending on your activities within its guild. Calculates weekly and leaderboards and generates custom profile banners with canvas. Has gambling commands such as coinflip and slots and weekly lottery draws. Made for, and used by the \"DayDream\" Discord guild.",
        icon: "/nyxLogo.png",
        technologies: ["Node.js", 'Discord.js', 'MongoDB', 'canvas'],
        url: null,
        color: '#6f6f6f',
        roundIcon: true,
    },
    {
        name: "Kuwai",
        type: 'Chatbot',
        description: "AI Chatbot using openAI's API. Remembers conversations and has its own personality.",
        icon: "/kuwaiLogo.png",
        technologies: ["Node.js", 'Discord.js', 'MongoDB'],
        url: null,
        color: '#dddafe',
        roundIcon: true,
    },
    {
        name: "UsefulScripts",
        type: 'Bash Scripts',
        description: "Scripts that take care of installing and configuring basic utilities for Linux distributions such as \"oh-my-zsh\", \"MongoDB\" and monitoring tools.",
        icon: "/bashscriptsLogo.jpg",
        technologies: ["Bash"],
        url: null,
        color: '#f4c224',
        roundIcon: true,
    },
];